---
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="100")
opts_chunk$set(# echo=TRUE,
	             cache = TRUE,
               prompt = FALSE,
               tidy = FALSE,
	             cache.lazy = FALSE,
               comment = NA,
               message = FALSE,
               warning = FALSE,
	             fig.align = "center",
	             fig.height = 5,
	             fig.width = 5)
opts_knit$set(width=100)
```

## 8. 마켓 데이터 분석   

### 8.1 데이터 전처리   

#### 8.1.1 데이터 및 패키지 불러오기  

```{r}
library(dplyr)
library(data.table)
library(ggplot2)
library(reshape)

DIR = "D:\\CSV\\Instacart\\"
LISTFILES = list.files(DIR)

for(k in 1:length(LISTFILES)){
  
  assign(gsub(".csv","",LISTFILES[k]),
         fread(paste0(DIR,LISTFILES[k])))
  
}
```

### 8.2 상위 판매 상품 분석   

#### 8.2.1 판매 상품 분석   

- 구매/재구매 상품 분석  

```{r}
Order_Id = order_products__prior %>%
  group_by(order_id) %>%
  summarise(Count = n(),
            Reordered = sum(reordered))

nrow(Order_Id)
summary(Order_Id$Count)
summary(Order_Id$Reordered)
```

```{r}
Order_Id$Reorder_Perc = Order_Id$Reordered / Order_Id$Count * 100 

summary(Order_Id$Reorder_Perc)
```

```{r}
ggplot(Order_Id) +
  geom_histogram(aes(x = Reorder_Perc), binwidth = 5) +
  xlab("Reorder Proportion") + ylab("Count") +
  theme_bw() 
```


```{r}
Order_products_Department = order_products__prior %>%
  inner_join(products, by = "product_id") %>%
  inner_join(departments, by = "department_id")
```

- 상품 카테고리별 판매 분석  

```{r}
Order_ID_Department = Order_products_Department %>%
  group_by(department) %>%
  summarise(Count = n(),
            Reordered = sum(reordered)) %>%
  mutate(NonReorder = Count - Reordered,
         Reorder_Perc = Reordered/Count * 100)

knitr::kable(Order_ID_Department %>%
               arrange(-Count))

Order_ID_Department %>%
  select(department, NonReorder, Reordered) %>%
  as.data.frame() %>%
  melt(id.vars = c("department")) %>%
  ggplot() +
  geom_bar(aes(x = reorder(department,value), y = value, fill = variable), stat = 'identity') +
  xlab("Department") + ylab("Sales Count") +
  labs(fill = "") +
  coord_flip() +
  theme_bw() +
  theme(legend.position = "bottom")
```

```{r}
Order_ID_Department %>%
  ggplot() +
  geom_bar(aes(x = reorder(department, Reorder_Perc), y = Reorder_Perc), stat = 'identity') +
  geom_label(aes(x = reorder(department, Reorder_Perc), y = Reorder_Perc, 
                 label = round(Reorder_Perc,2))) +
  xlab("Department") + ylab("Reorder Percent (%)") +
  labs(fill = "") +
  coord_flip() +
  theme_bw()
```

- 세부 상품별 판매 분석   

```{r}
Order_ID_Product = Order_products_Department %>%
  group_by(department,product_name) %>%
  summarise(Count = n(),
            Reordered = sum(reordered)) %>%
  mutate(NonReorder = Count - Reordered,
         Reorder_Perc = Reordered/Count * 100)

Order_ID_Product %>%
  ungroup() %>%
  top_n(n = 10, wt = Count)
```

```{r}
Product_Graph = function(Order_ID_Product, department_name){
  
  Graph = Order_ID_Product %>%
    filter(department == department_name) %>%
    ungroup() %>%
    top_n(n = 20, wt = Count) %>%
    select(department,product_name, NonReorder, Reordered) %>%
    as.data.frame() %>%
    melt(id.vars = c("department","product_name")) %>%
    ggplot() +
    geom_bar(aes(x = reorder(product_name,value), y = value, fill = variable), stat = 'identity') +
    xlab("product name") + ylab("Sales Count") +
    labs(fill = "") +
    coord_flip() +
    theme_bw() +
    theme(legend.position = "bottom") +
    ggtitle(department_name) 
  
  return(Graph)
  
}
```

```{r}
Product_Graph(Order_ID_Product = Order_ID_Product,
              department_name = "snacks")
```

### 8.3 고객 구매 패턴 분석   

#### 8.3.1 고객 재방문 시기 분석   

```{r}
orders_prior = orders %>%
  filter(eval_set == "prior")

User_Orders = orders_prior %>%
  group_by(user_id) %>%
  summarise(Count = n(),
            Revisit_Days_Mean = mean(days_since_prior_order, na.rm = TRUE),
            Revisit_Days_Median = median(days_since_prior_order, na.rm = TRUE),
            Revisit_Days_Mean = round(Revisit_Days_Mean,2),
            Revisit_Days_Median = round(Revisit_Days_Median,2)) 

knitr::kable(User_Orders[1:10,])
```

```{r}
User_Orders_Info = orders_prior %>%
  inner_join(Order_Id, by = "order_id") %>%
  group_by(user_id) %>%
  summarise(Count = n(),
            Revisit_Days_Mean = mean(days_since_prior_order, na.rm = TRUE),
            Revisit_Days_Median = median(days_since_prior_order, na.rm = TRUE),
            Revisit_Days_Mean = round(Revisit_Days_Mean,2),
            Revisit_Days_Median = round(Revisit_Days_Median,2),
            Reorder_Mean = mean(Reordered)) 

knitr::kable(User_Orders_Info[1:10,])
```

#### 8.3.2 고객 구매 물품 분석   

- 연관분석   

```{r}
# 데이터 무작위 추출

set.seed(1234)

Order_id = unique(Order_products_Department$order_id)

SL = sample(1:length(Order_id), length(Order_id) * 0.1)

Sample_Order_id = Order_id[SL]

Sample_Orders = Order_products_Department %>%
  filter(order_id %in% Sample_Order_id)

```

```{r}
# install.packages(“arules”) 
# install.packages(“arulesViz”)
library(arules) 
library(arulesViz)

DepartmentList = split(Sample_Orders$department,
                       Sample_Orders$order_id)

DepartmentList_trans = as(DepartmentList, "transactions")

summary(DepartmentList_trans)
```

```{r}
# 연관분석 진행

rules1 = apriori(DepartmentList_trans, 
                 parameter = list(support = 0.2, confidence = 0.1, minlen = 2))
rules1

rule.list1 = as.data.frame(inspect(rules1))
rule.list1

```

- 연관분석 시각화   

```{r}
plot(rules1)
 
plot(rules1, 
     method = "graph", 
     control = list(type="items"), 
     vertex.label.cex = 0.1, 
     edge.arrow.size = 0.1, 
     edge.arrow.width = 2)

plot(rules1, method = "grouped matrix")
```

#### 8.3.3 고객의 구매 패턴에 따른 군집 생성  

- 고객 패턴 데이터 생성   

```{r}
# reshape 패키지의 cast() 명령어 활요 

Orders_Department_Matrix = Order_products_Department %>%
  slice(1:10000) %>%
  select(order_id, department) %>%
  mutate(Count = 1) %>%
  reshape::cast(order_id~department,
                fun.aggregate = sum)


Orders_Department_Matrix

```

- tm 패키지의 Corpus(), DocumentMatrix() 명령어 활용   

```{r}
library(tm)
Order_products_Department$department2 = gsub(" ","",Order_products_Department$department)

Corpus = Corpus(VectorSource(Order_products_Department$department2[1:10000]))
DTM = DocumentTermMatrix(Corpus)
DTM_Matrix = as.matrix(DTM)
DTM_DF = as.data.frame(DTM_Matrix)
DTM_DF$order_id = Order_products_Department$order_id[1:10000]

Orders_Department_DF = DTM_DF
```


```{r}
# 구매 정보 데이터 생성  


set.seed(123)
SL = sample(1:length(Order_id), length(Order_id) * 0.1)

Sample_Order_id = Order_id[SL]

Sample_Orders = Order_products_Department %>%
  filter(order_id %in% Sample_Order_id)

Corpus2 = Corpus(VectorSource(Sample_Orders$department2))
DTM2 = DocumentTermMatrix(Corpus2)
DTM_Matrix2 = as.matrix(DTM2)
DTM_DF2 = as.data.frame(DTM_Matrix2)
DTM_DF2$order_id = Sample_Orders$order_id


Orders_Department_DF2 = DTM_DF2

DIR2 = "D:\\CSV\\"

fwrite(Orders_Department_DF2,
       paste0(DIR2,"Orders_Department_DF2.csv"))


```

```{r}
orders_prior = orders %>%
  filter(eval_set == "prior")

Orders_Department_DF2_Sum = Orders_Department_DF2 %>%
  group_by(order_id) %>%
  summarise_all(.funs = sum)

knitr::kable(Orders_Department_DF2_Sum[1:10,])
```

```{r}
Orders_Department_DF2_User = Orders_Department_DF2_Sum %>%
  inner_join(orders_prior, by = 'order_id')

User_Orders_Product = Orders_Department_DF2_User %>%
  select(-eval_set,-order_number,-order_dow,-order_id,
         -order_hour_of_day,-days_since_prior_order) %>%
  group_by(user_id) %>%
  summarise_all(.funs = mean)

User_Orders_Product
```

- 군집 분석   

```{r}
Sample_Orders_Info = orders_prior %>%
  filter(order_id %in% Order_id) %>%
  inner_join(Order_Id, by = "order_id") %>%
  group_by(user_id) %>%
  summarise(Count = n(),
            Revisit_Days_Mean = mean(days_since_prior_order, na.rm = TRUE),
            Revisit_Days_Mean = round(Revisit_Days_Mean,2),
            Reorder_Mean = mean(Reordered)) 


User_Orders_Info2 = Sample_Orders_Info %>%
  inner_join(User_Orders_Product, by = 'user_id') %>%
  as.data.frame()

knitr::kable(User_Orders_Info2[1:10,])
```

```{r}
Normalization = function(x){
  
  y = (x-min(x))/(max(x)-min(x))
  
  return(y)
  
}
```

```{r}
rownames(User_Orders_Info2) = User_Orders_Info2$user_id


User_Orders_Info2_2 = User_Orders_Info2 %>%
  select(-user_id)

User_Orders_Normalization = apply(User_Orders_Info2_2, 
                                  MARGIN = 2, 
                                  FUN = Normalization)

User_Orders_Normalization = as.data.frame(User_Orders_Normalization)

```


```{r}
library(factoextra)
library(FactoMineR)

set.seed(123)

SL = sample(1:nrow(User_Orders_Normalization),
            nrow(User_Orders_Normalization) * 0.05, 
            replace = FALSE)

k_cluster1 = kmeans(User_Orders_Normalization[SL,], 
                    2, nstart = 25)

fviz_cluster(k_cluster1, 
             data = User_Orders_Normalization[SL,],
             ellipse.type = "convex",
             palette = "jco",
             ggtheme = theme_minimal())

k_cluster2 = kmeans(User_Orders_Normalization[SL,], 3, nstart = 25)

fviz_cluster(k_cluster2, 
             data = User_Orders_Normalization[SL,],
             ellipse.type = "convex",
             palette = "jco",
             ggtheme = theme_minimal())
```

- 표준화 후 군집분석  

```{r}
User_Orders_Scale = scale(User_Orders_Info2_2)
User_Orders_Scale = as.data.frame(User_Orders_Scale)

k_cluster3 = kmeans(User_Orders_Scale[SL,], 2, nstart = 25)

fviz_cluster(k_cluster3, 
             data = User_Orders_Scale[SL,],
             ellipse.type = "convex",
             palette = "jco",
             ggtheme = theme_minimal())

k_cluster4 = kmeans(User_Orders_Scale[SL,], 3, nstart = 25)

fviz_cluster(k_cluster4, 
             data = User_Orders_Scale[SL,],
             ellipse.type = "convex",
             palette = "jco",
             ggtheme = theme_minimal())

```

- 군집 시각화   

```{r}
Sample_User = User_Orders_Scale[SL,]
Sample_User = as.data.frame(Sample_User)
Sample_User$Cluster = k_cluster4$cluster

Sample_User %>%
  group_by(Cluster) %>%
  summarise_all(.funs = mean) %>%
  as.data.frame() %>%
  melt(id.vars = c("Cluster")) %>%
  ggplot() +
  geom_point(aes(x = variable, y = value, col = as.factor(Cluster))) +
  geom_path(aes(x = variable, y = value, col = as.factor(Cluster),
                group = as.factor(Cluster))) +
  labs(col = "Cluster") +
  xlab("") + ylab("") +
  coord_polar() +
  theme_bw() +
  theme(legend.position = "bottom")
 

```

### 8.4 추천 시스템   

#### 8.4.2 추천 시스템 구현   

```{r}
# install.packages("recommenderlab")
library(recommenderlab)

rownames(User_Orders_Info2) = User_Orders_Info2$user_id

User_Orders_Info2_2 = User_Orders_Info2 %>%
  select(-user_id)

User_Orders_Scale = scale(User_Orders_Info2_2)
User_Orders_Scale = as.data.frame(User_Orders_Scale)

k_cluster_Total = kmeans(User_Orders_Scale, 3, nstart = 25)
User_Orders_Info2_2$Cluster = k_cluster_Total$cluster
```

- 추천 시스템을 위한 데이터 생성     

```{r}
Cluster3 = User_Orders_Info2_2 %>%
  filter(Cluster == 3) %>%
  select(-Count,-Revisit_Days_Mean,-Reorder_Mean, -Cluster)

Cluster3$user_id = paste0("user",rownames(Cluster3))
  
Cluster3 = Cluster3 %>%
  melt(id.vars = c("user_id")) %>%
  arrange(user_id)

C3_Matrix = as(Cluster3, "realRatingMatrix")

head(as(C3_Matrix, "data.frame"))
```


```{r}
C3_DF = as.data.frame(as(C3_Matrix, "data.frame"))

C3_DF$user = as.character(C3_DF$user)
C3_DF$item = as.character(C3_DF$item)

C3_DF %>%
  filter(user %in% c("user1","user2","user3","user4","user5")) %>%
  ggplot() +
  geom_tile(aes(x = user, y = item, fill = rating)) +
  geom_vline(xintercept = seq(0.5,by = 1, length.out = 9), 
             linetype = 'dashed') +
  geom_hline(yintercept = seq(0.5,by = 1, length.out = 26), 
             linetype = 'dashed') +
  scale_fill_gradientn(colours = c("white","black"),
                       values = c(0,0.5,1)) +
  theme_minimal() +
  labs(fill = "Rating") +
  theme(legend.position = "bottom",
        legend.key.width=unit(3,"cm"),
        text = element_text(size = 15, face = "bold"),
        legend.box.background =element_rect())
```

```{r}
C3_Ratings = getRatings(C3_Matrix)
summary(C3_Ratings)
```

- user Based   

```{r}
SL = 1:round(nrow(C3_Matrix)*0.99)

C3_Train = C3_Matrix[SL]
C3_Test = C3_Matrix[-SL]


C3_UBCF = Recommender(C3_Train, method = "UBCF")

```

```{r}
C3_U_Predict = predict(C3_UBCF, C3_Test, type="ratingMatrix") 

M3_U = as(C3_U_Predict,"matrix")
sort(colMeans(M3_U),decreasing = TRUE)
```


```{r}
sort(unlist(as(C3_U_Predict,"list")[1]),decreasing = TRUE)


```


```{r}
sort(unlist(as(C3_U_Predict,"list")[2]),decreasing = TRUE)
```

- Item BASED   

```{r}
C3_IBCF = Recommender(C3_Train, method = "IBCF")
C3_I_Predict = predict(C3_IBCF, C3_Test, type="ratingMatrix") 
M3_I = as(C3_I_Predict,"matrix")
sort(colMeans(M3_I),decreasing = TRUE)
```

```{r}
sort(unlist(as(C3_I_Predict,"list")[1]),decreasing = TRUE)

```

```{r}
print("Finish")
```

